apiVersion: v1
kind: Pod
metadata:
  name: function-probe
  labels:
    app: function-probe
spec:
  containers:
    - name: function-probe
      image: function-probe:0.1.0
      ports:
        - containerPort: 8080
          protocol: TCP