apiVersion: v1
kind: Service
metadata:
  name: media-function-probe
spec:
  type: NodePort
  selector:
    app: function-probe
  ports:
    - port: 8080
      nodePort: 30000
      protocol: TCP
      name: http
