apiVersion: v1
kind: Service
metadata:
  name: media-function-probe
spec:
  type: LoadBalancer
  selector:
    app: function-probe
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
